$:
  vscode:
    - docker:
        image: docker.cnb.cool/luojunhao/comfyuialpha:latest
      runner:
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: 初始化仓库和子模块
          script: |
            cd /workspace
            # 确保外层仓库正常
            git checkout main
            git pull origin main  # 拉取外层仓库最新配置
            
            # 初始化并更新子模块（关键步骤）
            git submodule init  # 初始化子模块配置
            git submodule update  # 拉取ComfyUI子模块内容
            
            # 进入子模块，确保是最新版本
            cd ComfyUI
            git pull origin master  # 拉取ComfyUI官方最新代码
            cd ..
            
            echo "子模块初始化完成，ComfyUI目录已就绪"