$:
  vscode:
    - docker:
        image:
          name: docker.cnb.cool/luojunhao/comfyuialpha:latest
          dockerUser: $CNB_TOKEN_USER_NAME
          dockerPassword: $CNB_TOKEN
      runner:
        tags: cnb:arch:amd64:gpu  # 仅保留必要的GPU标签，符合平台语法
      env:
        CNB_WELCOME_EXECUTE_COMMAND: bash /workspace/assets/main/update_comfyui_submodule.sh
      services:
        - vscode
        - docker
