$:
  vscode:
    - docker:
        image:
          name: docker.cnb.cool/luojunhao/comfyuialpha:latest
          dockerUser: $CNB_TOKEN_USER_NAME
          dockerPassword: $CNB_TOKEN
      runner:
        tags: cnb:arch:amd64:gpu
      env:
        CNB_WELCOME_EXECUTE_COMMAND: >
          bash /workspace/assets/nodes/node_manager.sh setup &&
          bash /workspace/assets/main/update_comfyui_submodule.sh
      services:
        - vscode
        - docker